CREATE TABLE Authors (
	AuthorID INT PRIMARY KEY IDENTITY (1,1),
	Name VARCHAR(100) NOT NULL
);
CREATE TABLE Books (
	BookID INT PRIMARY KEY IDENTITY (1,1),
	Title VARCHAR(100) NOT NULL,
	AuthorID INT FOREIGN KEY REFERENCES Authors(AuthorID)
);